    
print('start')
print('Q1 - good')
top5_by_genre('SCI-fi', 'C:/Users/user/Desktop/אוניברסיטת תא/סמסטר א/פייתון/תרגילי בית/ex 6/IMDB-Movie-Data.csv')
print('Q1 - io - no file')
top5_by_genre('action', 'C:/Users/user/Desktop/אוניברסיטת תא/סמסטר א/פייתון/תרגילי בית/ex 6/no-file.csv')
print('Q1 - no genre')
top5_by_genre('guy', 'C:/Users/user/Desktop/אוניברסיטת תא/סמסטר א/פייתון/תרגילי בית/ex 6/no-file.csv')
print('Q2 - 5*8')
print(mult(5,8))
print('Q2 - 10*1')
print(mult(10,1))
print('Q2 - 1*1')
print(mult(1,1))
print('Q3 - [1111.1111],1 ------ 0')
print(count_val([1111.1111],1))
print('Q3 - [1,2,3,4],12 --- 0')
print(count_val([1,2,3,4],12))
print('Q3 - [1,2,3,4],34 --- 0')
print(count_val([1,2,3,4],34))
print('Q3 - [],5) ---- 0')
print(count_val([],5))
print('Q3 - [" "]," ") ---- 1')
print(count_val([" "]," "))
print('Q3 -(Enterprise),r')
print(count_val(list('Enterprise'),'r'))
print('Q3 -(ABba),a ---1')
print(count_val(list('ABba'),'a'))
print('Q3 -(ABba),A ---- 1')
print(count_val(list('ABba'),'A'))
print('Q3 -(1/2),1 ----- 0')
print(count_val([1/2],1))
print('Q4.1 - 39')
print(climb_combinations(39))
print('Q4.2 - 39')
print(climb_combinations_memo(39))
print('Q5 - [],0,5  - True')
print(can_return_to_earth([],0, 5))
print('Q5 - [],1,5 - False')
print(can_return_to_earth([],1,5))
print('Q5 - [5,2,6,4,2],20,10  - False')
print(can_return_to_earth([5,2,6,4,2],20,10))
print('Q5 - [5,2,6,4,2],1,10  - False')
print(can_return_to_earth([5,2,6,4,2],1,10))

